server:
  port: 8080


spring:
  application:
    name: resource-server-security

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/oauth2/jwks

security:
  resource-id: Aservice
